stages:
  - publish_build_to_pre_qa

publish_build_to_pre_qa:
  stage: publish_build_to_pre_qa
  artifacts:
    when: always
    paths:
      - artifacts/*
  image: python:3.8-alpine
  before_script:
    - apk add --update --no-cache make curl bash git
    - curl -L https://github.com/screwdriver-cd/gitversion/releases/download/v1.1.1/gitversion_linux_amd64 -o /usr/local/bin/gitversion && chmod +x /usr/local/bin/gitversion
    - eval $(ssh-agent -s)
  script:
    - mkdir -p artifacts
    - pip install requests
    - python security_content_automation/publish_build_to_pre_qa/publish_build_to_pre_qa.py --version $CI_COMMIT_REF_NAME --builds DA-ESS-ContentUpdate
  after_script:
    - cp publish_build_to_pre_qa.log artifacts/publish_build_to_pre_qa.log
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^v[0-9]+\.[0-9]+\.[0-9]$/'
      when: always
