author: Teoderick Contreras, Splunk
datamodel:
- Endpoint.Processes
date: '2021-09-06'
description: This search is to detect a suspicious bcdedit commandline to configure
  the host to boot in safe mode with network config. This technique was seen in blackMatter
  ransomware where it force the compromised host to boot in safe mode to continue
  its encryption and bring back to normal boot using bcdedit deletevalue command.
  This TTP can be a good alert for host that booted from safe mode forcefully since
  it need to modify the boot configuration to bring it back to normal.
how_to_implement: To successfully implement this search, you need to be ingesting
  logs with the process name, parent process, and command-line executions from your
  endpoints. If you are using Sysmon, you must have at least version 6.0.4 of the
  Sysmon TA. Tune and filter known instances where renamed rundll32.exe may be used.
id: 81f1dce0-0f18-11ec-a5d7-acde48001122
known_false_positives: unknown
name: Change To Safe Mode With Network Config
references:
- https://news.sophos.com/en-us/2021/08/09/blackmatter-ransomware-emerges-from-the-shadow-of-darkside/
search: '| tstats `security_content_summariesonly` count min(_time) as firstTime max(_time)
  as lastTime from datamodel=Endpoint.Processes where Processes.process_name = bcdedit.exe
  Processes.process="*/set*" Processes.process="*{current}*"  Processes.process="*safeboot*"
  Processes.process="*network*" by Processes.process_name Processes.process Processes.parent_process_name
  Processes.dest Processes.user |`drop_dm_object_name(Processes)` | `security_content_ctime(firstTime)`
  | `security_content_ctime(lastTime)` | `change_to_safe_mode_with_network_config_filter`'
tags:
  analytic_story:
  - BlackMatter Ransomware
  automated_detection_testing: passed
  confidence: 50
  context:
  - Source:Endpoint
  - Stage:Impact
  dataset:
  - https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1552.002/autoadminlogon/windows-sysmon.log
  impact: 50
  kill_chain_phases:
  - Exploitation
  message: bcdedit process with commandline $process$ to force safemode boot the $dest$
  mitre_attack_id:
  - T1490
  observable:
  - name: user
    role:
    - Victim
    type: User
  - name: dest
    role:
    - Victim
    type: Hostname
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  required_fields:
  - Endpoint.Processes.dest
  - Endpoint.Processes.parent_process_name
  - Endpoint.Processes.process
  - Endpoint.Processes.process_name
  - Endpoint.Processes.user
  - _time
  risk_score: 25
  security_domain: endpoint
  supported_tas:
  - Splunk_TA_microsoft_sysmon
type: TTP
version: 1
