author: Teoderick Contreras, Splunk
datamodel:
- Endpoint
date: '2021-07-30'
description: this detection was designed to identifies suspicious spawned process
  of known MS office application due to macro or malicious code. this technique can
  be seen in so many malware like IcedID that used MS office as its weapon or attack
  vector to initially infect the machines.
how_to_implement: To successfully implement this search you need to be ingesting information
  on process that include the name of the process responsible for the changes from
  your endpoints into the `Endpoint` datamodel in the `Processes` node. In addition,
  confirm the latest CIM App 4.20 or higher is installed and the latest TA for the
  endpoint product.
id: 2d9fc90c-f11f-11eb-9300-acde48001122
known_false_positives: unknown
name: Office Application Spawn Regsvr32 process
references:
- https://www.joesandbox.com/analysis/380662/0/html
search: '| tstats `security_content_summariesonly` count min(_time) as firstTime max(_time)
  as lastTime from datamodel=Endpoint.Processes where (Processes.parent_process_name
  = "winword.exe" OR Processes.parent_process_name = "excel.exe" OR Processes.parent_process_name
  = "powerpnt.exe" OR Processes.parent_process_name = "outlook.exe") `process_regsvr32`
  by Processes.parent_process_name Processes.parent_process Processes.process_name
  Processes.original_file_name Processes.process Processes.process_id Processes.process_guid
  Processes.user Processes.dest | `drop_dm_object_name("Processes")` | `security_content_ctime(firstTime)`
  |`security_content_ctime(lastTime)` | `office_application_spawn_regsvr32_process_filter`'
tags:
  analytic_story:
  - IcedID
  automated_detection_testing: passed
  confidence: 90
  context:
  - Source:Endpoint
  - Stage:Execution
  dataset:
  - https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/malware/icedid/phish_icedid/windows-sysmon.log
  impact: 70
  kill_chain_phases:
  - Exploitation
  message: Office application spawning regsvr32.exe on $dest$
  mitre_attack_id:
  - T1566
  - T1566.001
  observable:
  - name: dest
    role:
    - Victim
    type: Endpoint
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  required_fields:
  - Processes.dest
  - Processes.original_file_name
  - Processes.parent_process
  - Processes.parent_process_name
  - Processes.process
  - Processes.process_guid
  - Processes.process_id
  - Processes.process_name
  - Processes.user
  - _time
  risk_score: 63
  security_domain: endpoint
type: TTP
version: 2
