name: Sdelete Application Execution
id: fcc52b9a-4616-11ec-8454-acde48001122
version: 1
date: '2021-11-15'
author: Teoderick Contreras, Splunk
type: Anomaly
datamodel:
- Endpoint_Processes
description: This analytic will detect the execution of sdelete.exe attempting to
  delete potentially important files that may related to adversary or insider threats
  to destroy evidence or information sabotage. Sdelete is a SysInternals utility meant
  to securely delete files on disk. This tool is commonly used to clear tracks and
  artifact on the targeted host.
search: '| from read_ssa_enriched_events() | eval timestamp=parse_long(ucast(map_get(input_event,"_time"),
  "string", null)), process=lower(ucast(map_get(input_event, "process"), "string",
  null)), process_name=lower(ucast(map_get(input_event, "process_name"), "string",
  null)), process_path=ucast(map_get(input_event, "process_path"), "string", null),
  parent_process_name=ucast(map_get(input_event, "parent_process_name"), "string",
  null), parent_process=ucast(map_get(input_event, "parent_process"), "string", null),
  event_id=ucast(map_get(input_event, "event_id"), "string", null), 
  dest_user_id=ucast(map_get(input_event, "dest_user_id"), "string", null),
  dest_device_id=ucast(map_get(input_event, "dest_device_id"), "string", null)
  | where process IS NOT NULL AND process_name IS NOT NULL AND like(process_name, "%sdelete%") AND
  (like (process, "%-c %") OR like (process, "%-f %")OR like (process, "%-p %")
  OR like (process, "%-r %") OR like (process, "%-q %") OR like (process, "%-s
  %") OR like (process, "%-z %") OR like (process, "%/accepteula%") OR like (process,
  "%-nobanner%")OR like (process, "%.doc%")OR like (process, "%.xls%") OR like (process,
  "%.ppt%")OR like (process, "%.rtf%") OR like (process, "%.pdf%") OR like (process,
  "%.key%")OR like (process, "%.log%") OR like (process, "%.txt%") OR like (process,
  "%.jpg%") OR like (process, "%.png%") OR like (process, "%.gif%") OR like (process,
  "%.bmp%") OR like (process, "%.7z%")  OR like (process, "%.zip%") OR like (process,
  "%.rar%") OR like (process, "%.tar%") OR like (process, "%.gz%") OR like (process,
  "%.xls%")) 
  | eval body=--body--
  | into write_ssa_finding_events();'
how_to_implement: To successfully implement this search you need to be ingesting information
  on process that include the name of the process responsible for the changes from
  your endpoints into the `Endpoint` datamodel in the `Processes` node. In addition,
  confirm the latest CIM App 4.20 or higher is installed and the latest TA for the
  endpoint product.
known_false_positives: False positives should be limited, filter as needed.
references:
- https://thedfirreport.com/2020/04/20/sqlserver-or-the-miner-in-the-basement/
- https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1485/T1485.md
tags:
  analytic_story:
  - Information Sabotage
  cis20: []
  confidence: 70
  context:
  - Source:Endpoint
  - Stage:Execution
  dataset:
  - https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1485/sdelete/security.log
  impact: 60
  kill_chain_phases:
  - Exploitation
  message: Sdelete process $process_name$ executed on $dest_device_id$ attempting
    to permanently delete files by $dest_user_id$.
  mitre_attack_id:
  - T1485
  - T1070.004
  - T1070
  nist: []
  observable:
  - name: dest_user_id
    type: User
    role:
    - Victim
  - name: dest_device_id
    type: Hostname
    role:
    - Victim
  - name: parent_process
    type: Process
    role:
    - Parent Process
  - name: process_name
    type: Process
    role:
    - Child Process
  product:
  - Splunk Behavioral Analytics
  required_fields:
  - _time
  - dest
  - user
  - parent_process_name
  - parent_process
  - process_name
  - process
  - process_id
  - process_path
  - process
  risk_score: 42
  risk_severity: low
  security_domain: endpoint
  asset_type: Endpoint
